#environment 配置对应的测试环境，可选项为dev,beta,release,us
environment: "local"
#robot_num 机器人个数
robot_num: 1
#uid_pre uid前缀(需保证每个人唯一)
uid_pre: 14070000
#scene 根据场景生成名字 1默认 2真实名字 3学校前缀
scene: 2
#event_id 活动id(必填)
event_id: "628f2f6d517b24fcbaa2a401"
#space_id spaceId可指定也可不设置，设置为""表示在event内的spaceId中随机选一个进入
space_id: "642529a2e0896482fad9e595"
#mode 模式 0-silence静默 1-normal正常 2-perpetual永动 3-follow跟随
mode: 0
#follow_player 跟随的队长id,配合mode=3使用，若为""，则在场景中随机选择一个跟随
follow_player: "3524109455"
#log_level 日志打印级别，推荐debug,info,error三个级别
log_level: "debug"